name: spotify-client
services:
  postgres:
    container_name: postgres
    image: postgres:16
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

  spoticlient:
    container_name: spoticlient
    restart: always
    build:
      context: .
    ports:
      - '127.0.0.1:${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_volume:
    name: postgres_prod_spoticlient
